### ISSUE TITLE
Not working on MacOs Monterey

### ISSUE THREAD

**Issue by wellenreiter** [cg2121/obs-soundboard#3] opened 2022-02-24 12:14 UTC
Excerpt from OBS-Logfile:

13:02:53.092: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-soundboard/bin/obs-soundboard.so->/Library/Application Support/obs-studio/plugins/obs-soundboard/bin/obs-soundboard.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-soundboard/bin/obs-soundboard.so, 0x0101): Library not loaded: /tmp/obsdeps/lib/QtWidgets.framework/Versions/5/QtWidgets
13:02:53.092:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-soundboard/bin/obs-soundboard.so
13:02:53.092:   Reason: tried: '/tmp/obsdeps/lib/QtWidgets.framework/Versions/5/QtWidgets' (no such file), '/System/Library/Frameworks/QtWidgets.framework/Versions/5/QtWidgets' (no such file)
13:02:53.092: 
13:02:53.093: Module '/Library/Application Support/obs-studio/plugins/obs-soundboard/bin/obs-soundboard.so' not loaded

**Comment by thomaslfessler** [comment] 2022-02-28 08:30
same problem on catalina.   V. 27.2. b3, 27.2.1 or 27.2.2.  x86 based mac.   Tried with 3 released versions.  None appear to work.  Is there a known working install config?

This may be caused by this issue:  https://stackoverflow.com/questions/30677457/dyld-library-not-loaded-when-using-qt-qtwebengine.

**Comment by cg2121** [comment] 2022-08-31 10:23
Should be fixed in next release.

**Closed by cg2121** 2022-08-31 10:23 UTC

**Comment by oscarviq** [comment] 2024-01-25 04:48
@cg2121 Any chance of that new release coming?
